/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hushset.app;

import hushset.list.LinkedList;
import hushset.set.Set;
import hushset.node.Node;

import java.util.ArrayList;
import java.util.Arrays;

public class App {
    public static void main(String[] args) {
        Node n1 = new Node("localhost:3001");
        Node n2 = new Node("localhost:3002");
        Node n3 = new Node("localhost:3003");

        ArrayList<Node> nodes = new ArrayList<>(Arrays.asList(n1, n2, n3));

        for (Node n : nodes) {
            System.out.println(n.id);
            n.setTable(nodes);
            System.out.println("--------------------");
        }

        System.out.println(n1.findSuccessor("hello").id);
        System.out.println(n1.findSuccessor("hel").id);
        System.out.println(n1.findSuccessor("world").id);
        System.out.println(n1.findSuccessor("dht").id);
        System.out.println(n1.findSuccessor("zero").id);
    }
}
