/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hushset.app;

import hushset.list.LinkedList;

import static hushset.utilities.StringUtils.join;
import static hushset.utilities.StringUtils.split;

import java.math.BigInteger;

import static hushset.app.MessageUtils.getMessage;

import org.apache.commons.codec.digest.*;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));

        String hash = "35454B055CC325EA1AF2126E27707052";
        String password = "ILoveJava";
        String md5Hex = DigestUtils
            .md5Hex(password); //.toUpperCase();

        System.out.println(md5Hex);
        // System.out.println(Integer.parseInt(md5Hex, 16));
        System.out.println(new BigInteger(md5Hex, 16));

    }
}
