/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hushset.app;

import hushset.list.LinkedList;
import hushset.set.Set;
import hushset.node.Node;

import static hushset.utilities.StringUtils.join;
import static hushset.utilities.StringUtils.split;
import static hushset.app.MessageUtils.getMessage;

import java.util.ArrayList;
import java.util.Arrays;

public class App {
    public static void main(String[] args) {
        Node n1 = new Node("localhost:3001");
        Node n2 = new Node("localhost:3002");
        Node n3 = new Node("localhost:3003");

        ArrayList<Node> nodes = new ArrayList<>(Arrays.asList(n1, n2, n3));

        for (Node n : nodes) {
            System.out.println(n.id);
            // System.out.println("---");
            // for (LinkedList<Integer> bb : set.buckets) {
            //     System.out.println(bb.toString());
            // }
            System.out.println("--------------------");
        }
    }
}
