/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("hushset.java-library-conventions")
}

dependencies {
    api(project(":list"))
    implementation("commons-codec:commons-codec:1.15")
}
