/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("hushset.java-application-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation("commons-codec:commons-codec:1.15")
    implementation("com.google.guava:guava:31.1-jre")
    implementation(project(":utilities"))
}

application {
    // Define the main class for the application.
    mainClass.set("hushset.app.App")
}
